// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oggvqzrftgdciarchsoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9nZ3ZxenJmdGdkY2lhcmNoc29oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0OTY5MDksImV4cCI6MjA1MjA3MjkwOX0.SRyPdD1B9myiuub3MxtJpMOMk6Gq3WjsBtXUjS34YQw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);